log:
    level: "debug"

data:
    movies: ".data/movies_head_10k.csv"
    ratings: ".data/ratings_head_10k.csv"
    credits: ".data/credits_head_10k.csv"

server:
    address: "server_0:12345"

batch:
    maxAmount: 10
