log:
    level: "INFO"

data:
    movies: ".data/movies_metadata.csv"
    ratings: ".data/ratings.csv"
    credits: ".data/credits.csv"

server:
    address: "server_0:12345"

batch:
    maxSize: 81920 # 80KB
