consts:
  filterExchange: "filterExchange"
  overviewExchange: "overviewExchange"
  mapExchange: "mapExchange"
  joinExchange: "joinExchange"
  reduceExchange: "reduceExchange"
  mergeExchange: "mergeExchange"
  topExchange: "topExchange"
  resultExchange: "resultExchange"
  broadcastId: ""

rabbitmq:
  SERVER:
    exchanges:
      filterExchange:
        name: "filterExchange"
        kind: "direct"

      overviewExchange:
        name: "overviewExchange"
        kind: "direct"

      joinExchange:
        name: "joinExchange"
        kind: "direct"

      resultExchange:
        name: "resultExchange"
        kind: "direct"

    binds:
      resultQueue:
        exchange: "resultExchange"

  FILTER:
    exchanges:
      filterExchange:
        name: "filterExchange"
        kind: "direct"

      joinExchange:
        name: "joinExchange"
        kind: "direct"

      mapExchange:
        name: "mapExchange"
        kind: "direct"

      resultExchange:
        name: "resultExchange"
        kind: "direct"

    queues:
      filterQueue:
        name: ""

    binds:
      filterQueue:
        exchange: "filterExchange"
        queue: ""

  OVERVIEWER:
    exchanges:
      overviewExchange:
        name: "overviewExchange"
        kind: "direct"

      mapExchange:
        name: "mapExchange"
        kind: "direct"

      resultExchange:
        name: "resultExchange"
        kind: "direct"

    queues:
      overviewQueue:
        name: ""

    binds:
      overviewQueue:
        exchange: "overviewExchange"
        queue: ""

  MAPPER:
    exchanges:
      mapExchange:
        name: "mapExchange"
        kind: "direct"

      reduceExchange:
        name: "reduceExchange"
        kind: "direct"

    queues:
      mapQueue:
        name: ""

    binds:
      mapQueue:
        exchange: "mapExchange"
        queue: ""

  JOINER:
    exchanges:
      joinExchange:
        name: "joinExchange"
        kind: "direct"

      mapExchange:
        name: "mapExchange"
        kind: "direct"

    queues:
      joinQueue:
        name: ""

    binds:
      joinQueue:
        exchange: "joinExchange"
        queue: ""

  REDUCER:
    exchanges:
      reduceExchange:
        name: "reduceExchange"
        kind: "direct"

      resultExchange:
        name: "resultExchange"
        kind: "direct"

      mergeExchange:
        name: "mergeExchange"
        kind: "direct"

      topExchange:
        name: "topExchange"
        kind: "direct"

    queues:
      reduceQueue:
        name: ""

    binds:
      reduceQueue:
        exchange: "reduceExchange"
        queue: ""

  REDUCER:
    exchanges:
      mergeExchange:
        name: "mergeExchange"
        kind: "direct"

      resultExchange:
        name: "resultExchange"
        kind: "direct"

      topExchange:
        name: "topExchange"
        kind: "direct"

    queues:
      mergeQueue:
        name: ""

    binds:
      mergeQueue:
        exchange: "mergeExchange"
        queue: "mergeExchange"

  TOPPER:
    exchanges:
      topExchange:
        name: "topExchange"
        kind: "direct"

      resultExchange:
        name: "resultExchange"
        kind: "direct"

    queues:
      topQueue:
        name: ""

    binds:
      topQueue:
        exchange: "topExchange"
        queue: ""

